### PR TITLE
Inline cursor dependency

### LINKED ISSUE #60: Stop depending on 8 year old package?
**Describe the bug**

This package depends on `cursors`, found here: https://github.com/dimerica-industries/node-cursor

This package produces the following deprecation warning:

(node:1340) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**What version are you on?**
1.1.4

**Expected behavior**
Do not emit a deprecation warning

**Additional context**
I opened this a while ago https://github.com/dimerica-industries/node-cursor/issues/1

I'm not exactly sure what the solution would be here. Maybe there's a different package that can be used? or maybe the 250 line functionality can be moved here.

### PR DESCRIPTION
**Pull request by EvanPurkhiser**
Fixes #60

This inlines and modernizes the `cursor` dependency.

This includes the Buffer deprecation https://github.com/dimerica-industries/node-cursor/pull/2 fix here

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Anyone able to take a look? cc @abuiles

**Review by Shaptic — APPROVED** [review]
Looks to be a straightforward inline of [node-cursor](https://github.com/dimerica-industries/node-cursor/blob/master/index.js) with a few modernizations; thanks! :heavy_check_mark:

**Comment by EvanPurkhiser** [comment]
Any chance on this making its way into a release any time soon? :)

**Comment by ire-and-curses** [comment]
@Shaptic any reason not to release this ASAP?

**Comment by Shaptic** [comment]
Nope, just flew under the radar. Will be a part of v1.3.0, see #66!

**Comment by EvanPurkhiser** [comment]
Thank you very much!

**Pull request merged**
